import { Chef, Experience, Review } from './types';

export const mockChefs: Chef[] = [
  {
    chefId: '1',
    userId: 'user1',
    name: 'Maria Rodriguez',
    bio: 'Authentic Italian cuisine specialist with 15 years of experience. Passionate about sharing traditional recipes passed down through generations.',
    cuisine_specialty: 'Italian',
    profile_picture_url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=400&fit=crop&crop=face',
    verification_status: 'verified',
    rating: 4.9,
    total_reviews: 127,
  },
  {
    chefId: '2',
    userId: 'user2',
    name: 'Kenji Tanaka',
    bio: 'Master sushi chef trained in Tokyo. Specializing in traditional Japanese techniques and seasonal ingredients.',
    cuisine_specialty: 'Japanese',
    profile_picture_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
    verification_status: 'verified',
    rating: 4.8,
    total_reviews: 89,
  },
  {
    chefId: '3',
    userId: 'user3',
    name: 'Sophie Laurent',
    bio: 'French pastry chef with expertise in classic desserts and modern interpretations. Former sous chef at Michelin-starred restaurants.',
    cuisine_specialty: 'French Pastry',
    profile_picture_url: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face',
    verification_status: 'verified',
    rating: 4.7,
    total_reviews: 156,
  },
];

export const mockExperiences: Experience[] = [
  {
    experienceId: '1',
    chefId: '1',
    title: 'Authentic Italian Pasta Making',
    description: 'Learn to make fresh pasta from scratch using traditional Italian techniques. We\'ll cover different pasta shapes and classic sauces.',
    price: 85,
    type: 'in-person',
    duration: 180,
    availability_slots: ['2024-01-15T14:00:00Z', '2024-01-16T10:00:00Z', '2024-01-17T16:00:00Z'],
    location: 'Downtown Culinary Studio, 123 Main St',
    image_url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&h=400&fit=crop',
    rating: 4.9,
    total_bookings: 45,
  },
  {
    experienceId: '2',
    chefId: '2',
    title: 'Sushi Masterclass: Nigiri & Rolls',
    description: 'Master the art of sushi making with proper knife techniques, rice preparation, and fish selection. Perfect for beginners and enthusiasts.',
    price: 120,
    type: 'in-person',
    duration: 150,
    availability_slots: ['2024-01-14T18:00:00Z', '2024-01-15T11:00:00Z'],
    location: 'Zen Kitchen, 456 Oak Ave',
    image_url: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=600&h=400&fit=crop',
    rating: 4.8,
    total_bookings: 32,
  },
  {
    experienceId: '3',
    chefId: '3',
    title: 'French Macaron Workshop',
    description: 'Create perfect macarons with proper technique, flavor combinations, and troubleshooting tips. Take home a dozen of your creations!',
    price: 95,
    type: 'virtual',
    duration: 120,
    availability_slots: ['2024-01-16T15:00:00Z', '2024-01-18T13:00:00Z'],
    virtual_link: 'https://zoom.us/j/example',
    ingredients_kit_details: 'Ingredient kit shipped 2 days before class',
    image_url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&h=400&fit=crop',
    rating: 4.7,
    total_bookings: 28,
  },
  {
    experienceId: '4',
    chefId: '1',
    title: 'Risotto Perfection Class',
    description: 'Master the creamy, perfect risotto with seasonal ingredients and wine pairing suggestions.',
    price: 75,
    type: 'in-person',
    duration: 120,
    availability_slots: ['2024-01-17T19:00:00Z', '2024-01-19T17:00:00Z'],
    location: 'Downtown Culinary Studio, 123 Main St',
    image_url: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&h=400&fit=crop',
    rating: 4.6,
    total_bookings: 21,
  },
];

export const mockReviews: Review[] = [
  {
    reviewId: '1',
    bookingId: 'booking1',
    rating: 5,
    comment: 'Amazing experience! Maria is such a talented teacher and the pasta was incredible.',
    review_time: '2024-01-10T20:00:00Z',
    user_name: 'Alex Chen',
  },
  {
    reviewId: '2',
    bookingId: 'booking2',
    rating: 5,
    comment: 'Best sushi class I\'ve ever taken. Kenji\'s attention to detail is phenomenal.',
    review_time: '2024-01-08T15:30:00Z',
    user_name: 'Sarah Johnson',
  },
  {
    reviewId: '3',
    bookingId: 'booking3',
    rating: 4,
    comment: 'Great virtual class! The ingredient kit was perfectly prepared and Sophie was very helpful.',
    review_time: '2024-01-05T14:15:00Z',
    user_name: 'Mike Davis',
  },
];
